### ISSUE TITLE
eShopOnAbp: Keycloak swagger authorization

### ISSUE THREAD

**Issue by hikalkan** [abpframework/eShopOnAbp#151] opened 2022-12-27 09:04 UTC
Moved from https://github.com/abpframework/abp/issues/14806

**Comment by alihdev** [comment] 2022-12-28 10:12
The cause of the issue is with :
1- **authorizationEndpoint** in **SwaggerConfigurationHelper**, which was resolved by update **Swashbuckle** to 6.0.1 and change to endpoint of keycloak auth instead of default.
2- **WebGateway_Swagger** and scopes that used by swagger .

Details in #147

**Comment by chimeramvp** [comment] 2023-02-09 03:59
Working after modified SwaggerConfigurationHelper like this
`
public static void ConfigureWithAuth(
        ServiceConfigurationContext context,
        string authority,
        Dictionary<string, string> scopes,
        string apiTitle,
        string apiVersion = "v1",
        string apiName = "v1"
    )
    {
        string authorizationEndpoint = "/protocol/openid-connect/auth", tokenEndpoint = "/protocol/openid-connect/token";
        var authorizationUrl = new Uri($"{authority.TrimEnd('/')}{authorizationEndpoint.EnsureStartsWith('/')}");
        var tokenUrl = new Uri($"{authority.TrimEnd('/')}{tokenEndpoint.EnsureStartsWith('/')}");

        context.Services
            .AddAbpSwaggerGen()
            .AddSwaggerGen(
                options =>
                {
                    options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                    {
                        Type = SecuritySchemeType.OAuth2,
                        Flows = new OpenApiOAuthFlows
                        {
                            AuthorizationCode = new OpenApiOAuthFlow
                            {
                                AuthorizationUrl = authorizationUrl,
                                Scopes = scopes,
                                TokenUrl = tokenUrl
                            }
                        }
                    });

                    options.AddSecurityRequirement(new OpenApiSecurityRequirement
                    {
                            {
                                new OpenApiSecurityScheme
                                {
                                    Reference = new OpenApiReference
                                    {
                                        Type = ReferenceType.SecurityScheme,
                                        Id = "oauth2"
                                    }
                                },
                                Array.Empty<string>()
                            }
                    });

                    options.SwaggerDoc(apiName, new OpenApiInfo { Title = apiTitle, Version = apiVersion });
                    options.DocInclusionPredicate((docName, description) => true);
                    options.CustomSchemaIds(type => type.FullName);
                });
    }`

**Comment by alihdev** [comment] 2023-02-09 05:18
> Working after modified SwaggerConfigurationHelper like this
> 
> ```
>     public static void ConfigureWithAuth(
>         ServiceConfigurationContext context,
>         string authority,
>         Dictionary<string, string> scopes,
>         string apiTitle,
>         string apiVersion = "v1",
>         string apiName = "v1"
>     )
>     {
>         string authorizationEndpoint = "/protocol/openid-connect/auth", tokenEndpoint = "/protocol/openid-connect/token";
>         var authorizationUrl = new Uri($"{authority.TrimEnd('/')}{authorizationEndpoint.EnsureStartsWith('/')}");
>         var tokenUrl = new Uri($"{authority.TrimEnd('/')}{tokenEndpoint.EnsureStartsWith('/')}");
> 
>         context.Services
>             .AddAbpSwaggerGen()
>             .AddSwaggerGen(
>                 options =>
>                 {
>                     options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
>                     {
>                         Type = SecuritySchemeType.OAuth2,
>                         Flows = new OpenApiOAuthFlows
>                         {
>                             AuthorizationCode = new OpenApiOAuthFlow
>                             {
>                                 AuthorizationUrl = authorizationUrl,
>                                 Scopes = scopes,
>                                 TokenUrl = tokenUrl
>                             }
>                         }
>                     });
> 
>                     options.AddSecurityRequirement(new OpenApiSecurityRequirement
>                     {
>                             {
>                                 new OpenApiSecurityScheme
>                                 {
>                                     Reference = new OpenApiReference
>                                     {
>                                         Type = ReferenceType.SecurityScheme,
>                                         Id = "oauth2"
>                                     }
>                                 },
>                                 Array.Empty<string>()
>                             }
>                     });
> 
>                     options.SwaggerDoc(apiName, new OpenApiInfo { Title = apiTitle, Version = apiVersion });
>                     options.DocInclusionPredicate((docName, description) => true);
>                     options.CustomSchemaIds(type => type.FullName);
>                 });
>     }
> ```

check : https://github.com/abpframework/eShopOnAbp/pull/147/files#

**Comment by chimeramvp** [comment] 2023-02-09 05:53
> 

get it. thanks!

**Comment by chimeramvp** [comment] 2023-02-09 05:53
> 

get it. thanks!

**Closed** 2024-02-22 02:15 UTC
