### ISSUE TITLE
Findings in the project.

### ISSUE THREAD

**Issue by EngincanV** [abpframework/eShopOnAbp#263] opened 2024-07-29 06:50 UTC
- [x] Missing method exception while updating user info on keycloack. ( Done: https://github.com/abpframework/eShopOnAbp/commit/71842636916bba3cfe04d23e9b53216d57a75043 ✅  )
- [ ] Unable to add an item to the basket on https://eshoponabp.com/
- [ ] Missing/wrong localization in angular project.
- [ ] checking for other problems...

**Comment by berkansasmaz** [comment] 2024-07-29 06:55
This issue could be a duplicate of [this one](https://github.com/volosoft/volo/issues/17762).

**Comment by EngincanV** [comment] 2024-07-29 06:59
> This issue could be a duplicate of [this one](https://github.com/volosoft/volo/issues/17762).

I'll fix some common problems, then you can test the eshoponabp in general. It would be better in that way, so we can eliminate common problems and find tricky ones (and fix them). Currently, being not able to add an item to the basket is a huge problem and make the demo application not testable.

**Comment by berkansasmaz** [comment] 2024-08-02 06:47
I discussed with @EngincanV and it was decided that this issue is a duplicate.

**Closed by berkansasmaz** 2024-08-02 06:47 UTC
